# Generated by Django 4.0.3 on 2022-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_chead0_remove_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
